
name: C/C++ with Make

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make main.c
    - name: make check
      run: make check main.c
    - name: make distcheck
      run: make distcheck
